import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../services/api_service.dart';
import '../../models/vehicle.dart';

class AddVehiclePage extends StatefulWidget {
  @override
  _AddVehiclePageState createState() => _AddVehiclePageState();
}

class _AddVehiclePageState extends State<AddVehiclePage> {
  final _formKey = GlobalKey<FormState>();
  final _modelController = TextEditingController();
  final _yearController = TextEditingController();
  final _engineController = TextEditingController();
  final _chassisController = TextEditingController();
  final _seatingController = TextEditingController();
  final _safetyRatingController = TextEditingController();
  final _topSpeedController = TextEditingController();
  final _priceController = TextEditingController();
  final _quantityController = TextEditingController();

  bool _isLoading = false;

  void _submit() async {
    if (_formKey.currentState!.validate()) {
      setState(() {
        _isLoading = true;
      });

      final vehicle = Vehicle(
        id: 0, // Assuming ID is auto-generated by the backend
        model: _modelController.text,
        year: int.parse(_yearController.text),
        engine: _engineController.text,
        chassis: _chassisController.text,
        seatingCapacity: int.parse(_seatingController.text),
        safetyRating: double.parse(_safetyRatingController.text),
        topSpeed: double.parse(_topSpeedController.text),
        price: double.parse(_priceController.text),
        quantity: int.parse(_quantityController.text),
      );

      final apiService = Provider.of<ApiService>(context, listen: false);
      final response = await apiService.addVehicle(vehicle);

      setState(() {
        _isLoading = false;
      });

      if (response.statusCode == 201) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Vehicle added successfully')),
        );
        Navigator.pop(context);
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Failed to add vehicle')),
        );
      }
    }
  }

  @override
  void dispose() {
    _modelController.dispose();
    _yearController.dispose();
    _engineController.dispose();
    _chassisController.dispose();
    _seatingController.dispose();
    _safetyRatingController.dispose();
    _topSpeedController.dispose();
    _priceController.dispose();
    _quantityController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('Add Vehicle'),
        ),
        body: Padding(
          padding: const EdgeInsets.all(16.0),
          child: _isLoading
              ? Center(child: CircularProgressIndicator())
              : Form(
            key: _formKey,
            child: ListView(
              children: [
                TextFormField(
                  controller: _modelController,
                  decoration: InputDecoration(labelText: 'Model'),
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please enter the model';
                    }
                    return null;
                  },
                ),
                TextFormField(
                  controller: _yearController,
                  decoration: InputDecoration(labelText: 'Year'),
                  keyboardType: TextInputType.number,
                  validator: (value) {
                    if (value == null ||
                        value.isEmpty ||
                        int.tryParse(value) == null) {
                      return 'Please enter a valid year';
                    }
                    return null;
                  },
                ),
                TextFormField(
                  controller: _engineController,
                  decoration: InputDecoration(labelText: 'Engine'),
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please enter the engine details';
                    }
                    return null;
                  },
                ),
                TextFormField(
                  controller: _chassisController,
                  decoration: InputDecoration(labelText: 'Chassis'),
                  validator: (value) {
                    if (value == null || value.isEmpty) {
                      return 'Please enter the chassis details';
                    }
                    return null;
                  },
                ),
                TextFormField(
                  controller: _seatingController,
                  decoration:
                  InputDecoration(labelText: 'Seating Capacity'),
                  keyboardType: TextInputType.number,
                  validator: (value) {
                    if (value == null ||
                        value.isEmpty ||
                        int.tryParse(value) == null) {
                      return 'Please enter a valid seating capacity';
                    }
                    return null;
                  },
                ),
                TextFormField(
                  controller: _safetyRatingController,
                  decoration: InputDecoration(labelText: 'Safety Rating'),
                  keyboardType:
                  TextInputType.numberWithOptions(decimal: true),
                  validator: (value) {
                    if (value == null ||
                        value.isEmpty ||
                        double.tryParse(value) == null) {
                      return 'Please enter a valid safety rating';
                    }
                    return null;
                  },
                ),
                TextFormField(
                  controller: _topSpeedController,
                  decoration: InputDecoration(labelText: 'Top Speed'),
                  keyboardType:
                  TextInputType.numberWithOptions(decimal: true),
                  validator: (value) {
                    if (value == null ||
                        value.isEmpty ||
                        double.tryParse(value) == null) {
                      return 'Please enter a valid top speed';
                    }
                    return null;
                  },
                ),
                TextFormField(
                  controller: _priceController,
                  decoration: InputDecoration(labelText: 'Price'),
                  keyboardType:
                  TextInputType.numberWithOptions(decimal: true),
                  validator: (value) {
                    if (value == null ||
                        value.isEmpty ||
                        double.tryParse(value) == null) {
                      return 'Please enter a valid price';
                    }
                    return null;
                  },
                ),
                TextFormField(
                  controller: _quantityController,
                  decoration: InputDecoration(labelText: 'Quantity'),
                  keyboardType: TextInputType.number,
                  validator: (value) {
                    if (value == null ||
                        value.isEmpty ||
                        int.tryParse(value) == null) {
                      return 'Please enter a valid quantity';
                    }
                    return null;
                  },
                ),
                SizedBox(height: 20),
                ElevatedButton(
                  onPressed: _submit,
                  child: Text('Add Vehicle'),
                ),
              ],
            ),
          ),
        ));
  }
}
